# Generated by Django 4.2.5 on 2023-09-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_app', '0002_buyerinfo_companyinfo_product_producttype_vendorinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
