# Generated by Django 4.2.5 on 2023-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_app', '0002_alter_userinfo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerinfo',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
    ]
